apiVersion: batch/v1
kind: Job
metadata:
  name: param-secret-sync
spec:
  backoffLimit: 1
  completions: 1
  parallelism: 1
  template:
    spec:
      containers:
      - image: qwilt/param-secret-sync-amd64:0.1
        name: param-secret-sync
        imagePullPolicy: IfNotPresent
        args: ["-params", "/dev/docker-login", "-type", "kubernetes.io/dockercfg"]
        env:
        - name: AWS_REGION
          value: YOUR-REGION 
        - name: AWS_ACCESS_KEY_ID
          value: YOUR-ACCESS-KEY-ID
        - name: AWS_SECRET_ACCESS_KEY
          value: YOUR-AWSr-SECRET-ACCESS-KEY
      restartPolicy: Never
